// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package datadb

import (
	"database/sql"
)

type TrackMbidMap struct {
	FeiniuGuid       string         `json:"feiniu_guid"`
	FilePath         sql.NullString `json:"file_path"`
	Title            sql.NullString `json:"title"`
	Artist           sql.NullString `json:"artist"`
	Album            sql.NullString `json:"album"`
	RecordingMbid    sql.NullString `json:"recording_mbid"`
	ReleaseMbid      sql.NullString `json:"release_mbid"`
	ReleaseGroupMbid sql.NullString `json:"release_group_mbid"`
	ArtistMbid       sql.NullString `json:"artist_mbid"`
	WorkMbid         sql.NullString `json:"work_mbid"`
	MatchedBy        string         `json:"matched_by"`
	UpdatedAt        string         `json:"updated_at"`
}
