// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package datadb

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteTrackMBID(ctx context.Context, feiniuGuid string) error
	GetTrackMBID(ctx context.Context, feiniuGuid string) (TrackMbidMap, error)
	GetTrackMBIDByPath(ctx context.Context, filePath sql.NullString) (TrackMbidMap, error)
	ListTrackMBIDs(ctx context.Context) ([]TrackMbidMap, error)
	UpsertTrackMBID(ctx context.Context, arg UpsertTrackMBIDParams) (TrackMbidMap, error)
}

var _ Querier = (*Queries)(nil)
