// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type PlaybackLog struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	TokenPrefix sql.NullString `json:"token_prefix"`
	Guid        sql.NullString `json:"guid"`
	Title       string         `json:"title"`
	Artist      sql.NullString `json:"artist"`
	Album       sql.NullString `json:"album"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	StartedAt   string         `json:"started_at"`
	EndedAt     sql.NullString `json:"ended_at"`
	CreatedAt   string         `json:"created_at"`
}

type RunStatus struct {
	Username              string         `json:"username"`
	LastfmScrobbles       int64          `json:"lastfm_scrobbles"`
	ListenbrainzScrobbles int64          `json:"listenbrainz_scrobbles"`
	TotalScrobbles        int64          `json:"total_scrobbles"`
	LastfmEnabled         int64          `json:"lastfm_enabled"`
	ListenbrainzEnabled   int64          `json:"listenbrainz_enabled"`
	LastScrobbledAt       sql.NullString `json:"last_scrobbled_at"`
	UpdatedAt             string         `json:"updated_at"`
}

type SyncLog struct {
	ID         int64          `json:"id"`
	Username   string         `json:"username"`
	Provider   string         `json:"provider"`
	Status     string         `json:"status"`
	Trigger    string         `json:"trigger"`
	Playlists  int64          `json:"playlists"`
	Tracks     int64          `json:"tracks"`
	Message    sql.NullString `json:"message"`
	StartedAt  string         `json:"started_at"`
	FinishedAt string         `json:"finished_at"`
}

type TrackMbidMap struct {
	FeiniuGuid       string         `json:"feiniu_guid"`
	FilePath         sql.NullString `json:"file_path"`
	Title            sql.NullString `json:"title"`
	Artist           sql.NullString `json:"artist"`
	Album            sql.NullString `json:"album"`
	RecordingMbid    sql.NullString `json:"recording_mbid"`
	ReleaseMbid      sql.NullString `json:"release_mbid"`
	ReleaseGroupMbid sql.NullString `json:"release_group_mbid"`
	ArtistMbid       sql.NullString `json:"artist_mbid"`
	WorkMbid         sql.NullString `json:"work_mbid"`
	MatchedBy        string         `json:"matched_by"`
	UpdatedAt        string         `json:"updated_at"`
}

type User struct {
	ID               int64          `json:"id"`
	Username         string         `json:"username"`
	PlatformUid      sql.NullString `json:"platform_uid"`
	PlatformUsername sql.NullString `json:"platform_username"`
	IsAdmin          int64          `json:"is_admin"`
	TokenPrefix      string         `json:"token_prefix"`
	UaRaw            sql.NullString `json:"ua_raw"`
	UaSystem         sql.NullString `json:"ua_system"`
	UaClient         sql.NullString `json:"ua_client"`
	FirstSeenAt      string         `json:"first_seen_at"`
	LastSeenAt       string         `json:"last_seen_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}
