// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type RunStatus struct {
	Username              string         `json:"username"`
	LastfmScrobbles       int64          `json:"lastfm_scrobbles"`
	ListenbrainzScrobbles int64          `json:"listenbrainz_scrobbles"`
	TotalScrobbles        int64          `json:"total_scrobbles"`
	LastfmEnabled         int64          `json:"lastfm_enabled"`
	ListenbrainzEnabled   int64          `json:"listenbrainz_enabled"`
	LastScrobbledAt       sql.NullString `json:"last_scrobbled_at"`
	UpdatedAt             string         `json:"updated_at"`
}

type User struct {
	ID               int64          `json:"id"`
	Username         string         `json:"username"`
	PlatformUid      sql.NullString `json:"platform_uid"`
	PlatformUsername sql.NullString `json:"platform_username"`
	IsAdmin          int64          `json:"is_admin"`
	TokenPrefix      sql.NullString `json:"token_prefix"`
	UaRaw            sql.NullString `json:"ua_raw"`
	UaSystem         sql.NullString `json:"ua_system"`
	UaClient         sql.NullString `json:"ua_client"`
	FirstSeenAt      string         `json:"first_seen_at"`
	LastSeenAt       string         `json:"last_seen_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}
