// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const bindUserPlatform = `-- name: BindUserPlatform :exec
UPDATE users
SET
  platform_uid = ?1,
  platform_username = ?2,
  is_admin = ?3,
  updated_at = ?4
WHERE
  username = ?5
`

type BindUserPlatformParams struct {
	PlatformUid      sql.NullString `json:"platform_uid"`
	PlatformUsername sql.NullString `json:"platform_username"`
	IsAdmin          int64          `json:"is_admin"`
	UpdatedAt        string         `json:"updated_at"`
	Username         string         `json:"username"`
}

func (q *Queries) BindUserPlatform(ctx context.Context, arg BindUserPlatformParams) error {
	_, err := q.db.ExecContext(ctx, bindUserPlatform,
		arg.PlatformUid,
		arg.PlatformUsername,
		arg.IsAdmin,
		arg.UpdatedAt,
		arg.Username,
	)
	return err
}

const getRunStatus = `-- name: GetRunStatus :one
SELECT
  username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
FROM
  run_status
WHERE
  username = ?1
`

func (q *Queries) GetRunStatus(ctx context.Context, username string) (RunStatus, error) {
	row := q.db.QueryRowContext(ctx, getRunStatus, username)
	var i RunStatus
	err := row.Scan(
		&i.Username,
		&i.LastfmScrobbles,
		&i.ListenbrainzScrobbles,
		&i.TotalScrobbles,
		&i.LastfmEnabled,
		&i.ListenbrainzEnabled,
		&i.LastScrobbledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunStatusTotal = `-- name: GetRunStatusTotal :one
SELECT
  COALESCE(SUM(total_scrobbles), 0) AS total,
  COALESCE(SUM(lastfm_scrobbles), 0) AS lastfm,
  COALESCE(SUM(listenbrainz_scrobbles), 0) AS listenbrainz,
  COUNT(*) AS user_count
FROM
  run_status
`

type GetRunStatusTotalRow struct {
	Total        interface{} `json:"total"`
	Lastfm       interface{} `json:"lastfm"`
	Listenbrainz interface{} `json:"listenbrainz"`
	UserCount    int64       `json:"user_count"`
}

func (q *Queries) GetRunStatusTotal(ctx context.Context) (GetRunStatusTotalRow, error) {
	row := q.db.QueryRowContext(ctx, getRunStatusTotal)
	var i GetRunStatusTotalRow
	err := row.Scan(
		&i.Total,
		&i.Lastfm,
		&i.Listenbrainz,
		&i.UserCount,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
  id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
FROM
  users
WHERE
  username = ?1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PlatformUid,
		&i.PlatformUsername,
		&i.IsAdmin,
		&i.TokenPrefix,
		&i.UaRaw,
		&i.UaSystem,
		&i.UaClient,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementScrobble = `-- name: IncrementScrobble :one
UPDATE run_status
SET
  lastfm_scrobbles = lastfm_scrobbles + CASE
    WHEN ?1 = 'lastfm' THEN 1
    ELSE 0
  END,
  listenbrainz_scrobbles = listenbrainz_scrobbles + CASE
    WHEN ?1 = 'listenbrainz' THEN 1
    ELSE 0
  END,
  total_scrobbles = total_scrobbles + 1,
  last_scrobbled_at = ?2,
  updated_at = ?3
WHERE
  username = ?4 RETURNING username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
`

type IncrementScrobbleParams struct {
	Provider        interface{}    `json:"provider"`
	LastScrobbledAt sql.NullString `json:"last_scrobbled_at"`
	UpdatedAt       string         `json:"updated_at"`
	Username        string         `json:"username"`
}

func (q *Queries) IncrementScrobble(ctx context.Context, arg IncrementScrobbleParams) (RunStatus, error) {
	row := q.db.QueryRowContext(ctx, incrementScrobble,
		arg.Provider,
		arg.LastScrobbledAt,
		arg.UpdatedAt,
		arg.Username,
	)
	var i RunStatus
	err := row.Scan(
		&i.Username,
		&i.LastfmScrobbles,
		&i.ListenbrainzScrobbles,
		&i.TotalScrobbles,
		&i.LastfmEnabled,
		&i.ListenbrainzEnabled,
		&i.LastScrobbledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunStatus = `-- name: ListRunStatus :many
SELECT
  username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
FROM
  run_status
ORDER BY
  total_scrobbles DESC,
  username ASC
`

func (q *Queries) ListRunStatus(ctx context.Context) ([]RunStatus, error) {
	rows, err := q.db.QueryContext(ctx, listRunStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunStatus{}
	for rows.Next() {
		var i RunStatus
		if err := rows.Scan(
			&i.Username,
			&i.LastfmScrobbles,
			&i.ListenbrainzScrobbles,
			&i.TotalScrobbles,
			&i.LastfmEnabled,
			&i.ListenbrainzEnabled,
			&i.LastScrobbledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
FROM
  users
ORDER BY
  last_seen_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PlatformUid,
			&i.PlatformUsername,
			&i.IsAdmin,
			&i.TokenPrefix,
			&i.UaRaw,
			&i.UaSystem,
			&i.UaClient,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserSeen = `-- name: TouchUserSeen :one
UPDATE users
SET
  last_seen_at = ?1,
  updated_at = ?2
WHERE
  username = ?3 RETURNING id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
`

type TouchUserSeenParams struct {
	LastSeenAt string `json:"last_seen_at"`
	UpdatedAt  string `json:"updated_at"`
	Username   string `json:"username"`
}

func (q *Queries) TouchUserSeen(ctx context.Context, arg TouchUserSeenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, touchUserSeen, arg.LastSeenAt, arg.UpdatedAt, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PlatformUid,
		&i.PlatformUsername,
		&i.IsAdmin,
		&i.TokenPrefix,
		&i.UaRaw,
		&i.UaSystem,
		&i.UaClient,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRunStatus = `-- name: UpsertRunStatus :one
INSERT INTO
  run_status (
    username,
    lastfm_enabled,
    listenbrainz_enabled,
    last_scrobbled_at,
    updated_at
  )
VALUES
  (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
  ) ON CONFLICT (username) DO
UPDATE
SET
  lastfm_enabled = excluded.lastfm_enabled,
  listenbrainz_enabled = excluded.listenbrainz_enabled,
  updated_at = excluded.updated_at RETURNING username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
`

type UpsertRunStatusParams struct {
	Username            string         `json:"username"`
	LastfmEnabled       int64          `json:"lastfm_enabled"`
	ListenbrainzEnabled int64          `json:"listenbrainz_enabled"`
	LastScrobbledAt     sql.NullString `json:"last_scrobbled_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) UpsertRunStatus(ctx context.Context, arg UpsertRunStatusParams) (RunStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertRunStatus,
		arg.Username,
		arg.LastfmEnabled,
		arg.ListenbrainzEnabled,
		arg.LastScrobbledAt,
		arg.UpdatedAt,
	)
	var i RunStatus
	err := row.Scan(
		&i.Username,
		&i.LastfmScrobbles,
		&i.ListenbrainzScrobbles,
		&i.TotalScrobbles,
		&i.LastfmEnabled,
		&i.ListenbrainzEnabled,
		&i.LastScrobbledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO
  users (
    username,
    platform_uid,
    platform_username,
    is_admin,
    token_prefix,
    ua_raw,
    ua_system,
    ua_client,
    first_seen_at,
    last_seen_at,
    created_at,
    updated_at
  )
VALUES
  (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
  ) ON CONFLICT (token_prefix) DO
UPDATE
SET
  username = excluded.username,
  platform_uid = COALESCE(excluded.platform_uid, users.platform_uid),
  platform_username = COALESCE(
    excluded.platform_username,
    users.platform_username
  ),
  is_admin = users.is_admin,
  ua_raw = CASE
    WHEN excluded.ua_raw IS NOT NULL
    AND excluded.ua_raw != '' THEN excluded.ua_raw
    ELSE users.ua_raw
  END,
  ua_system = CASE
    WHEN excluded.ua_system IS NOT NULL
    AND excluded.ua_system != '' THEN excluded.ua_system
    ELSE users.ua_system
  END,
  ua_client = CASE
    WHEN excluded.ua_client IS NOT NULL
    AND excluded.ua_client != '' THEN excluded.ua_client
    ELSE users.ua_client
  END,
  last_seen_at = excluded.last_seen_at,
  updated_at = excluded.updated_at RETURNING id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
`

type UpsertUserParams struct {
	Username         string         `json:"username"`
	PlatformUid      sql.NullString `json:"platform_uid"`
	PlatformUsername sql.NullString `json:"platform_username"`
	IsAdmin          int64          `json:"is_admin"`
	TokenPrefix      string         `json:"token_prefix"`
	UaRaw            sql.NullString `json:"ua_raw"`
	UaSystem         sql.NullString `json:"ua_system"`
	UaClient         sql.NullString `json:"ua_client"`
	FirstSeenAt      string         `json:"first_seen_at"`
	LastSeenAt       string         `json:"last_seen_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.Username,
		arg.PlatformUid,
		arg.PlatformUsername,
		arg.IsAdmin,
		arg.TokenPrefix,
		arg.UaRaw,
		arg.UaSystem,
		arg.UaClient,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PlatformUid,
		&i.PlatformUsername,
		&i.IsAdmin,
		&i.TokenPrefix,
		&i.UaRaw,
		&i.UaSystem,
		&i.UaClient,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
