// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	BindUserPlatform(ctx context.Context, arg BindUserPlatformParams) error
	GetRunStatus(ctx context.Context, username string) (RunStatus, error)
	GetRunStatusTotal(ctx context.Context) (GetRunStatusTotalRow, error)
	GetUser(ctx context.Context, username string) (User, error)
	IncrementScrobble(ctx context.Context, arg IncrementScrobbleParams) (RunStatus, error)
	ListRunStatus(ctx context.Context) ([]RunStatus, error)
	ListUsers(ctx context.Context) ([]User, error)
	TouchUserSeen(ctx context.Context, arg TouchUserSeenParams) (User, error)
	UpsertRunStatus(ctx context.Context, arg UpsertRunStatusParams) (RunStatus, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
