// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const bindUserPlatform = `-- name: BindUserPlatform :exec
UPDATE users
SET
  platform_uid = ?1,
  platform_username = ?2,
  is_admin = ?3,
  updated_at = ?4
WHERE
  username = ?5
`

type BindUserPlatformParams struct {
	PlatformUid      sql.NullString `json:"platform_uid"`
	PlatformUsername sql.NullString `json:"platform_username"`
	IsAdmin          int64          `json:"is_admin"`
	UpdatedAt        string         `json:"updated_at"`
	Username         string         `json:"username"`
}

func (q *Queries) BindUserPlatform(ctx context.Context, arg BindUserPlatformParams) error {
	_, err := q.db.ExecContext(ctx, bindUserPlatform,
		arg.PlatformUid,
		arg.PlatformUsername,
		arg.IsAdmin,
		arg.UpdatedAt,
		arg.Username,
	)
	return err
}

const closeOpenPlaybacks = `-- name: CloseOpenPlaybacks :exec
UPDATE playback_log
SET
  ended_at = ?1
WHERE
  ended_at IS NULL
`

func (q *Queries) CloseOpenPlaybacks(ctx context.Context, endedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, closeOpenPlaybacks, endedAt)
	return err
}

const getLastSuccessTime = `-- name: GetLastSuccessTime :one
SELECT
  finished_at
FROM
  sync_log
WHERE
  username = ?1
  AND provider = ?2
  AND status = 'success'
ORDER BY
  finished_at DESC
LIMIT
  1
`

type GetLastSuccessTimeParams struct {
	Username string `json:"username"`
	Provider string `json:"provider"`
}

func (q *Queries) GetLastSuccessTime(ctx context.Context, arg GetLastSuccessTimeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastSuccessTime, arg.Username, arg.Provider)
	var finished_at string
	err := row.Scan(&finished_at)
	return finished_at, err
}

const getRunStatus = `-- name: GetRunStatus :one
SELECT
  username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
FROM
  run_status
WHERE
  username = ?1
`

func (q *Queries) GetRunStatus(ctx context.Context, username string) (RunStatus, error) {
	row := q.db.QueryRowContext(ctx, getRunStatus, username)
	var i RunStatus
	err := row.Scan(
		&i.Username,
		&i.LastfmScrobbles,
		&i.ListenbrainzScrobbles,
		&i.TotalScrobbles,
		&i.LastfmEnabled,
		&i.ListenbrainzEnabled,
		&i.LastScrobbledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunStatusTotal = `-- name: GetRunStatusTotal :one
SELECT
  COALESCE(SUM(total_scrobbles), 0) AS total,
  COALESCE(SUM(lastfm_scrobbles), 0) AS lastfm,
  COALESCE(SUM(listenbrainz_scrobbles), 0) AS listenbrainz,
  COUNT(*) AS user_count
FROM
  run_status
`

type GetRunStatusTotalRow struct {
	Total        interface{} `json:"total"`
	Lastfm       interface{} `json:"lastfm"`
	Listenbrainz interface{} `json:"listenbrainz"`
	UserCount    int64       `json:"user_count"`
}

func (q *Queries) GetRunStatusTotal(ctx context.Context) (GetRunStatusTotalRow, error) {
	row := q.db.QueryRowContext(ctx, getRunStatusTotal)
	var i GetRunStatusTotalRow
	err := row.Scan(
		&i.Total,
		&i.Lastfm,
		&i.Listenbrainz,
		&i.UserCount,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
  id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
FROM
  users
WHERE
  username = ?1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PlatformUid,
		&i.PlatformUsername,
		&i.IsAdmin,
		&i.TokenPrefix,
		&i.UaRaw,
		&i.UaSystem,
		&i.UaClient,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementScrobble = `-- name: IncrementScrobble :one
UPDATE run_status
SET
  lastfm_scrobbles = lastfm_scrobbles + CASE
    WHEN ?1 = 'lastfm' THEN 1
    ELSE 0
  END,
  listenbrainz_scrobbles = listenbrainz_scrobbles + CASE
    WHEN ?1 = 'listenbrainz' THEN 1
    ELSE 0
  END,
  total_scrobbles = total_scrobbles + 1,
  last_scrobbled_at = ?2,
  updated_at = ?3
WHERE
  username = ?4 RETURNING username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
`

type IncrementScrobbleParams struct {
	Provider        interface{}    `json:"provider"`
	LastScrobbledAt sql.NullString `json:"last_scrobbled_at"`
	UpdatedAt       string         `json:"updated_at"`
	Username        string         `json:"username"`
}

func (q *Queries) IncrementScrobble(ctx context.Context, arg IncrementScrobbleParams) (RunStatus, error) {
	row := q.db.QueryRowContext(ctx, incrementScrobble,
		arg.Provider,
		arg.LastScrobbledAt,
		arg.UpdatedAt,
		arg.Username,
	)
	var i RunStatus
	err := row.Scan(
		&i.Username,
		&i.LastfmScrobbles,
		&i.ListenbrainzScrobbles,
		&i.TotalScrobbles,
		&i.LastfmEnabled,
		&i.ListenbrainzEnabled,
		&i.LastScrobbledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlayback = `-- name: InsertPlayback :one
INSERT INTO
  playback_log (
    username,
    token_prefix,
    guid,
    title,
    artist,
    album,
    duration_ms,
    started_at,
    ended_at,
    created_at
  )
VALUES
  (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
  ) RETURNING id
`

type InsertPlaybackParams struct {
	Username    string         `json:"username"`
	TokenPrefix sql.NullString `json:"token_prefix"`
	Guid        sql.NullString `json:"guid"`
	Title       string         `json:"title"`
	Artist      sql.NullString `json:"artist"`
	Album       sql.NullString `json:"album"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	StartedAt   string         `json:"started_at"`
	EndedAt     sql.NullString `json:"ended_at"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertPlayback(ctx context.Context, arg InsertPlaybackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPlayback,
		arg.Username,
		arg.TokenPrefix,
		arg.Guid,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationMs,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSyncLog = `-- name: InsertSyncLog :one
INSERT INTO
  sync_log (
    username,
    provider,
    status,
    trigger,
    playlists,
    tracks,
    message,
    started_at,
    finished_at
  )
VALUES
  (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
  ) RETURNING id, username, provider, status, "trigger", playlists, tracks, message, started_at, finished_at
`

type InsertSyncLogParams struct {
	Username   string         `json:"username"`
	Provider   string         `json:"provider"`
	Status     string         `json:"status"`
	Trigger    string         `json:"trigger"`
	Playlists  int64          `json:"playlists"`
	Tracks     int64          `json:"tracks"`
	Message    sql.NullString `json:"message"`
	StartedAt  string         `json:"started_at"`
	FinishedAt string         `json:"finished_at"`
}

func (q *Queries) InsertSyncLog(ctx context.Context, arg InsertSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRowContext(ctx, insertSyncLog,
		arg.Username,
		arg.Provider,
		arg.Status,
		arg.Trigger,
		arg.Playlists,
		arg.Tracks,
		arg.Message,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Provider,
		&i.Status,
		&i.Trigger,
		&i.Playlists,
		&i.Tracks,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listPlaybacksByUser = `-- name: ListPlaybacksByUser :many
SELECT
  id,
  username,
  token_prefix,
  guid,
  title,
  artist,
  album,
  duration_ms,
  started_at,
  ended_at,
  created_at
FROM
  playback_log
WHERE
  username = ?1
ORDER BY
  started_at DESC
LIMIT
  ?2
`

type ListPlaybacksByUserParams struct {
	Username  string `json:"username"`
	LimitRows int64  `json:"limit_rows"`
}

func (q *Queries) ListPlaybacksByUser(ctx context.Context, arg ListPlaybacksByUserParams) ([]PlaybackLog, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybacksByUser, arg.Username, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaybackLog{}
	for rows.Next() {
		var i PlaybackLog
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TokenPrefix,
			&i.Guid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlaybacks = `-- name: ListRecentPlaybacks :many
SELECT
  id,
  username,
  token_prefix,
  guid,
  title,
  artist,
  album,
  duration_ms,
  started_at,
  ended_at,
  created_at
FROM
  playback_log
ORDER BY
  started_at DESC
LIMIT
  ?1
`

func (q *Queries) ListRecentPlaybacks(ctx context.Context, limitRows int64) ([]PlaybackLog, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlaybacks, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaybackLog{}
	for rows.Next() {
		var i PlaybackLog
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TokenPrefix,
			&i.Guid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSyncLogs = `-- name: ListRecentSyncLogs :many
SELECT
  id, username, provider, status, "trigger", playlists, tracks, message, started_at, finished_at
FROM
  sync_log
ORDER BY
  finished_at DESC
LIMIT
  ?1
`

func (q *Queries) ListRecentSyncLogs(ctx context.Context, limitRows int64) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSyncLogs, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Provider,
			&i.Status,
			&i.Trigger,
			&i.Playlists,
			&i.Tracks,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunStatus = `-- name: ListRunStatus :many
SELECT
  username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
FROM
  run_status
ORDER BY
  total_scrobbles DESC,
  username ASC
`

func (q *Queries) ListRunStatus(ctx context.Context) ([]RunStatus, error) {
	rows, err := q.db.QueryContext(ctx, listRunStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunStatus{}
	for rows.Next() {
		var i RunStatus
		if err := rows.Scan(
			&i.Username,
			&i.LastfmScrobbles,
			&i.ListenbrainzScrobbles,
			&i.TotalScrobbles,
			&i.LastfmEnabled,
			&i.ListenbrainzEnabled,
			&i.LastScrobbledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncLogsByUser = `-- name: ListSyncLogsByUser :many
SELECT
  id, username, provider, status, "trigger", playlists, tracks, message, started_at, finished_at
FROM
  sync_log
WHERE
  username = ?1
ORDER BY
  finished_at DESC
LIMIT
  ?2
`

type ListSyncLogsByUserParams struct {
	Username  string `json:"username"`
	LimitRows int64  `json:"limit_rows"`
}

func (q *Queries) ListSyncLogsByUser(ctx context.Context, arg ListSyncLogsByUserParams) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, listSyncLogsByUser, arg.Username, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Provider,
			&i.Status,
			&i.Trigger,
			&i.Playlists,
			&i.Tracks,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
FROM
  users
ORDER BY
  last_seen_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PlatformUid,
			&i.PlatformUsername,
			&i.IsAdmin,
			&i.TokenPrefix,
			&i.UaRaw,
			&i.UaSystem,
			&i.UaClient,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithUARaw = `-- name: ListUsersWithUARaw :many
SELECT
  id,
  ua_raw
FROM
  users
WHERE
  ua_raw IS NOT NULL
  AND ua_raw != ''
`

type ListUsersWithUARawRow struct {
	ID    int64          `json:"id"`
	UaRaw sql.NullString `json:"ua_raw"`
}

func (q *Queries) ListUsersWithUARaw(ctx context.Context) ([]ListUsersWithUARawRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithUARaw)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithUARawRow{}
	for rows.Next() {
		var i ListUsersWithUARawRow
		if err := rows.Scan(&i.ID, &i.UaRaw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAgent = `-- name: SetUserAgent :exec
UPDATE users
SET
  ua_system = ?1,
  ua_client = ?2
WHERE
  id = ?3
`

type SetUserAgentParams struct {
	UaSystem sql.NullString `json:"ua_system"`
	UaClient sql.NullString `json:"ua_client"`
	ID       int64          `json:"id"`
}

func (q *Queries) SetUserAgent(ctx context.Context, arg SetUserAgentParams) error {
	_, err := q.db.ExecContext(ctx, setUserAgent, arg.UaSystem, arg.UaClient, arg.ID)
	return err
}

const touchUserSeenByToken = `-- name: TouchUserSeenByToken :exec
UPDATE users
SET
  last_seen_at = ?1,
  updated_at = ?2
WHERE
  token_prefix = ?3
`

type TouchUserSeenByTokenParams struct {
	LastSeenAt  string `json:"last_seen_at"`
	UpdatedAt   string `json:"updated_at"`
	TokenPrefix string `json:"token_prefix"`
}

func (q *Queries) TouchUserSeenByToken(ctx context.Context, arg TouchUserSeenByTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchUserSeenByToken, arg.LastSeenAt, arg.UpdatedAt, arg.TokenPrefix)
	return err
}

const updatePlaybackEndedAt = `-- name: UpdatePlaybackEndedAt :exec
UPDATE playback_log
SET
  ended_at = ?1
WHERE
  id = ?2
`

type UpdatePlaybackEndedAtParams struct {
	EndedAt sql.NullString `json:"ended_at"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdatePlaybackEndedAt(ctx context.Context, arg UpdatePlaybackEndedAtParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaybackEndedAt, arg.EndedAt, arg.ID)
	return err
}

const upsertRunStatus = `-- name: UpsertRunStatus :one
INSERT INTO
  run_status (
    username,
    lastfm_enabled,
    listenbrainz_enabled,
    last_scrobbled_at,
    updated_at
  )
VALUES
  (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
  ) ON CONFLICT (username) DO
UPDATE
SET
  lastfm_enabled = excluded.lastfm_enabled,
  listenbrainz_enabled = excluded.listenbrainz_enabled,
  updated_at = excluded.updated_at RETURNING username, lastfm_scrobbles, listenbrainz_scrobbles, total_scrobbles, lastfm_enabled, listenbrainz_enabled, last_scrobbled_at, updated_at
`

type UpsertRunStatusParams struct {
	Username            string         `json:"username"`
	LastfmEnabled       int64          `json:"lastfm_enabled"`
	ListenbrainzEnabled int64          `json:"listenbrainz_enabled"`
	LastScrobbledAt     sql.NullString `json:"last_scrobbled_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) UpsertRunStatus(ctx context.Context, arg UpsertRunStatusParams) (RunStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertRunStatus,
		arg.Username,
		arg.LastfmEnabled,
		arg.ListenbrainzEnabled,
		arg.LastScrobbledAt,
		arg.UpdatedAt,
	)
	var i RunStatus
	err := row.Scan(
		&i.Username,
		&i.LastfmScrobbles,
		&i.ListenbrainzScrobbles,
		&i.TotalScrobbles,
		&i.LastfmEnabled,
		&i.ListenbrainzEnabled,
		&i.LastScrobbledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO
  users (
    username,
    platform_uid,
    platform_username,
    is_admin,
    token_prefix,
    ua_raw,
    ua_system,
    ua_client,
    first_seen_at,
    last_seen_at,
    created_at,
    updated_at
  )
VALUES
  (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
  ) ON CONFLICT (token_prefix) DO
UPDATE
SET
  username = excluded.username,
  platform_uid = COALESCE(excluded.platform_uid, users.platform_uid),
  platform_username = COALESCE(
    excluded.platform_username,
    users.platform_username
  ),
  is_admin = users.is_admin,
  ua_raw = CASE
    WHEN excluded.ua_raw IS NOT NULL
    AND excluded.ua_raw != '' THEN excluded.ua_raw
    ELSE users.ua_raw
  END,
  ua_system = CASE
    WHEN excluded.ua_system IS NOT NULL
    AND excluded.ua_system != '' THEN excluded.ua_system
    ELSE users.ua_system
  END,
  ua_client = CASE
    WHEN excluded.ua_client IS NOT NULL
    AND excluded.ua_client != '' THEN excluded.ua_client
    ELSE users.ua_client
  END,
  last_seen_at = excluded.last_seen_at,
  updated_at = excluded.updated_at RETURNING id, username, platform_uid, platform_username, is_admin, token_prefix, ua_raw, ua_system, ua_client, first_seen_at, last_seen_at, created_at, updated_at
`

type UpsertUserParams struct {
	Username         string         `json:"username"`
	PlatformUid      sql.NullString `json:"platform_uid"`
	PlatformUsername sql.NullString `json:"platform_username"`
	IsAdmin          int64          `json:"is_admin"`
	TokenPrefix      string         `json:"token_prefix"`
	UaRaw            sql.NullString `json:"ua_raw"`
	UaSystem         sql.NullString `json:"ua_system"`
	UaClient         sql.NullString `json:"ua_client"`
	FirstSeenAt      string         `json:"first_seen_at"`
	LastSeenAt       string         `json:"last_seen_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.Username,
		arg.PlatformUid,
		arg.PlatformUsername,
		arg.IsAdmin,
		arg.TokenPrefix,
		arg.UaRaw,
		arg.UaSystem,
		arg.UaClient,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PlatformUid,
		&i.PlatformUsername,
		&i.IsAdmin,
		&i.TokenPrefix,
		&i.UaRaw,
		&i.UaSystem,
		&i.UaClient,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
